In [ ]:
import numpy as np

#Basics


In [ ]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Get Dimentions
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
#Get shape
b.shape

(2, 4)

In [ ]:
#Get Type
a.dtype

dtype('int16')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

2

In [ ]:
b.itemsize

8

In [ ]:
# Get a specific element [r, c]

In [ ]:
c  = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get specific element by index
c[1,5]

13

In [ ]:
c[1, -2]

13

In [ ]:
#Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get specific column
c[:, 3]

array([ 4, 11])

In [ ]:
# Get requires set of element like List
c[0, 1:5:2]
#Prints 1 to 5 elements in 2 space

array([2, 4])

In [ ]:
#Changing the elements same like List
c[1, 5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
#We can change an entire row or colums value
c[: , 3] = 100
print(c)

[[  1   2   3 100   5   6   7]
 [  8   9  10 100  12  20  14]]


In [ ]:
c[:, 2] = [50, 50]
print(c)

[[  1   2  50 100   5   6   7]
 [  8   9  50 100  12  20  14]]


#3D Numpy Array


In [ ]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element
d[0, 1, 1]

4

In [ ]:
# Changing the element also same
d[1, 0, 1] = 50
print(d)

[[[ 1  2]
  [ 3  4]]

 [[ 5 50]
  [ 7  8]]]


In [ ]:
# Changing more values
d[:, 1, :] = [[90, 90], [10, 10]]
print(d)

[[[ 1  2]
  [90 90]]

 [[ 5 50]
  [10 10]]]


# Initializing different types of Arrays

In [ ]:
#All zeros matrix
np.zeros((2,4))
#np.zeros((2,4,2,5))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#All one matrix
np.ones((4,4), dtype = 'int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
#Like 0s and 1s , Any other numbers , full keyword is used
np.full((3,3),99)
#np.full((3,3),99 , dtype = 'float32')

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [ ]:
#Changing all element in our old variable
np.full_like(b, 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
#Random decimal numbers
np.random.rand(3,2)
#np.random.rand(3,2,3)


#If i want in other arrays dimentions
np.random.random_sample(b.shape)

array([[0.0396793 , 0.88681613, 0.4736096 , 0.53811534],
       [0.58643711, 0.63602394, 0.4622689 , 0.03321553]])

In [ ]:
#Random Integers values 0 to 7
np.random.randint(7, size = (3,3))

# 4 to 7
np.random.randint(4,7, size = (3,3))

array([[6, 6, 5],
       [4, 4, 5],
       [6, 5, 5]])

In [ ]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array n num of times

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3 , axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
##Practice##

ot = np.ones((5,5))
z = np.zeros((3,3))
print(ot)
z[1,1] = 9
print(z)

ot[1:4, 1:4]= z
#ot[1:-1, 1:-1]= z
print(ot)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful while copying an array

In [ ]:
a = np.array([1,2,3])
#b = a
# this will making changes in b also affect the A

# So we use copy method
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematics

In [ ]:
a = np.array([1,2,4,5])
print(a)

#So we can apply math to every element easily

[1 2 4 5]


In [ ]:
a+2

array([3, 4, 6, 7])

In [ ]:
a-2

array([-1,  0,  2,  3])

In [ ]:
a*3

array([ 3,  6, 12, 15])

In [ ]:
a/2

array([0.5, 1. , 2. , 2.5])

In [ ]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 5, 5])

In [ ]:
a ** b

array([1, 1, 4, 1])

In [ ]:
# Taking sin, cosine anything
np.sin(a)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427])

In [ ]:
# Mathematical operations Documentation
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),3)
print(b)

# These are in diff dimensions so direct mul wont work
# So we use matrix mul
print("Matrix Multiplication Value")
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
Matrix Multiplication Value


array([[9., 9.],
       [9., 9.]])

In [ ]:
# Finding the determinant

c = np.identity(3) # identity 3 X 3 matrix
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#min max
np.min(stats)
np.max(stats)

6

In [ ]:
# Print the max value in all array
np.max(stats, axis = 1)

array([3, 6])

In [ ]:
# sum of the all elements

np.sum(stats)

21

## Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal stacking vector

h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#  Miscellaneous

Load data from files

In [ ]:
filedata = np.genfromtxt('numpydata.txt', delimiter=',')
filedata.astype('int32')
filedata
# we need a file with text data like
# 1,2,3,4,5
# 6,7,8,9,10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Boolean Masking and Advaned indexing

In [ ]:
# check the num is greater than 5 or not
filedata > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# returns the value only greater than 5
filedata[filedata > 5]

array([ 6.,  7.,  8.,  9., 10.])

In [ ]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8])
print(a)

#Gives the values at the index
a[[1,2,5]]

[1 2 3 4 5 6 7 8]


array([2, 3, 6])

In [ ]:
# np.any(filedata > 50 , axis = 0)
# prints the column of all nums greater than 50

In [ ]:
# Prints the boolean value for this condition for all num
(filedata > 5) & (filedata < 7)

array([False, False, False, False, False,  True, False, False, False,
       False])

In [ ]:
###Practice
x = np.zeros((6,5))
print(x)
print()

x = np.zeros((6,5))
x[2:4, 0:2]=1
print(x)
print()

x = np.zeros((6,5))
x[[0,1,2,3],[1,2,3,4]] = 1
print(x)
print()

x = np.zeros((6,5))
x[[0,4,5],3:] = 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
